export type AutomationPipelineKey = "sales" | "realization" | "complaints";
export type AutomationProfile = "starter" | "full";
export type AutomationPriority = "P0" | "P1" | "P2";
export type AutomationKind =
  | "plan_activity"
  | "create_task"
  | "notify_employee"
  | "modify_field"
  | "end_tasks"
  | "add_history_entry"
  | "sales_tunnel_move";

export interface AutomationTiming {
  mode: "immediately" | "after" | "before_field" | "at_field";
  value?: number;
  unit?: "minutes" | "hours" | "business_hours" | "days" | "business_days";
  fieldAlias?: string;
  respectBusinessHours?: boolean;
}

export interface AutomationCondition {
  field: string;
  operator: "equals" | "not_empty";
  value?: string;
}

export interface AutomationRuleBlueprint {
  id: string;
  pipeline: AutomationPipelineKey;
  stageCode: string;
  priority: AutomationPriority;
  profiles: AutomationProfile[];
  kind: AutomationKind;
  name: string;
  execution: "parallel" | "sequential";
  timing: AutomationTiming;
  conditions?: AutomationCondition[];
  settings: Record<string, unknown>;
  acceptance: string[];
  notes?: string[];
}

const starterAndFull: AutomationProfile[] = ["starter", "full"];
const fullOnly: AutomationProfile[] = ["full"];

export const MOONGLASS_AUTOMATION_BLUEPRINT_VERSION = "2026-08-05.1";

export const MOONGLASS_AUTOMATION_RULES: AutomationRuleBlueprint[] = [
  {
    id: "S01_ACTIVITY_FIRST_CONTACT",
    pipeline: "sales",
    stageCode: "MG_NEW",
    priority: "P0",
    profiles: starterAndFull,
    kind: "plan_activity",
    name: "[MG] Pierwszy kontakt z klientem",
    execution: "parallel",
    timing: { mode: "immediately", respectBusinessHours: true },
    settings: {
      activityType: "call",
      subject: "Pierwszy kontakt — {{Deal: Title}}",
      description:
        "Skontaktuj się z klientem, zweryfikuj potrzeby i uzupełnij notatkę w Dealu. Po rozmowie przesuń Deal do właściwego etapu.",
      deadline: "+2 godziny robocze",
      responsible: "Osoba odpowiedzialna za Deal",
      autoCompleteOnStageChange: true,
    },
    acceptance: [
      "Po utworzeniu nowego Deala w osi czasu pojawia się aktywność kontaktu.",
      "Aktywność jest przypisana do osoby odpowiedzialnej za Deal.",
    ],
  },
  {
    id: "S02_TASK_NEW_INQUIRY",
    pipeline: "sales",
    stageCode: "MG_NEW",
    priority: "P0",
    profiles: starterAndFull,
    kind: "create_task",
    name: "[MG] Obsłuż nowe zapytanie",
    execution: "parallel",
    timing: { mode: "immediately", respectBusinessHours: true },
    settings: {
      title: "Obsłuż nowe zapytanie — {{Deal: Title}}",
      description:
        "1. Sprawdź telefon i e-mail.\n2. Wykonaj pierwszy kontakt.\n3. Uzupełnij notatkę.\n4. Przesuń Deal do: Brak kontaktu, Kontakt nawiązany albo Przegrany — zła kwalifikacja.",
      deadline: "+4 godziny robocze",
      assignee: "Osoba odpowiedzialna za Deal",
      linkToCrmItem: true,
    },
    acceptance: ["Powstaje jedno zadanie powiązane z Dealem."],
  },
  {
    id: "S03_NOTIFY_STALE_NEW",
    pipeline: "sales",
    stageCode: "MG_NEW",
    priority: "P1",
    profiles: fullOnly,
    kind: "notify_employee",
    name: "[MG] Nowe zapytanie nadal bez obsługi",
    execution: "parallel",
    timing: { mode: "after", value: 1, unit: "business_days", respectBusinessHours: true },
    settings: {
      recipients: "Osoba odpowiedzialna za Deal",
      message:
        "Deal {{Deal: Title}} nadal znajduje się w etapie Nowe zapytanie. Zweryfikuj kontakt i ustaw właściwy etap.",
    },
    acceptance: ["Powiadomienie uruchamia się tylko, jeśli Deal nadal pozostaje w tym etapie."],
  },
  {
    id: "S04_ACTIVITY_NO_CONTACT",
    pipeline: "sales",
    stageCode: "MG_NOCONTACT",
    priority: "P0",
    profiles: starterAndFull,
    kind: "plan_activity",
    name: "[MG] Ponów kontakt z klientem",
    execution: "parallel",
    timing: { mode: "after", value: 1, unit: "business_days", respectBusinessHours: true },
    settings: {
      activityType: "call",
      subject: "Druga próba kontaktu — {{Deal: Title}}",
      description: "Ponów kontakt. Po próbie uzupełnij notatkę i zaktualizuj etap Deala.",
      deadline: "W dniu uruchomienia reguły",
      responsible: "Osoba odpowiedzialna za Deal",
      autoCompleteOnStageChange: true,
    },
    acceptance: ["Po jednym dniu roboczym pojawia się aktywność drugiej próby kontaktu."],
  },
  {
    id: "S05_ACTIVITY_NO_CONTACT_LAST",
    pipeline: "sales",
    stageCode: "MG_NOCONTACT",
    priority: "P1",
    profiles: fullOnly,
    kind: "plan_activity",
    name: "[MG] Ostatnia próba kontaktu",
    execution: "parallel",
    timing: { mode: "after", value: 3, unit: "business_days", respectBusinessHours: true },
    settings: {
      activityType: "call",
      subject: "Ostatnia próba kontaktu — {{Deal: Title}}",
      description:
        "Wykonaj ostatnią próbę kontaktu. Jeśli klient nadal nie odpowiada, wybierz odpowiedni etap i wpisz powód.",
      responsible: "Osoba odpowiedzialna za Deal",
      autoCompleteOnStageChange: true,
    },
    acceptance: ["Reguła nie wykonuje się po opuszczeniu etapu Brak kontaktu."],
  },
  {
    id: "S06_TASK_QUALIFICATION",
    pipeline: "sales",
    stageCode: "MG_CONTACT",
    priority: "P0",
    profiles: starterAndFull,
    kind: "create_task",
    name: "[MG] Uzupełnij kwalifikację klienta",
    execution: "parallel",
    timing: { mode: "immediately", respectBusinessHours: true },
    settings: {
      title: "Uzupełnij kwalifikację — {{Deal: Title}}",
      description:
        "Uzupełnij: lokalizację, typ produktu, oczekiwany termin, budżet, status zdjęć i informację, czy wymagany jest pomiar.",
      deadline: "+1 dzień roboczy",
      assignee: "Osoba odpowiedzialna za Deal",
      linkToCrmItem: true,
    },
    acceptance: ["Po wejściu do etapu Kontakt nawiązany powstaje zadanie kwalifikacji."],
  },
  {
    id: "S07_ACTIVITY_PHOTOS_REMINDER",
    pipeline: "sales",
    stageCode: "MG_PHOTOS",
    priority: "P0",
    profiles: starterAndFull,
    kind: "plan_activity",
    name: "[MG] Przypomnij o zdjęciach",
    execution: "parallel",
    timing: { mode: "after", value: 2, unit: "business_days", respectBusinessHours: true },
    settings: {
      activityType: "call",
      subject: "Przypomnienie o zdjęciach — {{Deal: Title}}",
      description: "Skontaktuj się z klientem w sprawie brakujących zdjęć lub wymiarów miejsca montażu.",
      responsible: "Osoba odpowiedzialna za Deal",
      autoCompleteOnStageChange: true,
    },
    acceptance: ["Po dwóch dniach roboczych powstaje przypomnienie, jeśli Deal nadal czeka na zdjęcia."],
  },
  {
    id: "S08_TASK_NEXT_STEP",
    pipeline: "sales",
    stageCode: "MG_QUAL",
    priority: "P1",
    profiles: fullOnly,
    kind: "create_task",
    name: "[MG] Ustal pomiar albo przygotowanie oferty",
    execution: "parallel",
    timing: { mode: "immediately", respectBusinessHours: true },
    settings: {
      title: "Ustal następny krok — {{Deal: Title}}",
      description:
        "Sprawdź pole Czy wymagany pomiar. Przenieś Deal do Pomiar do umówienia albo Przygotowanie oferty.",
      deadline: "+1 dzień roboczy",
      assignee: "Osoba odpowiedzialna za Deal",
      linkToCrmItem: true,
    },
    acceptance: ["Zakwalifikowany Deal otrzymuje jedno zadanie określenia następnego kroku."],
  },
  {
    id: "S09_ACTIVITY_AFTER_QUAL_NO_CONTACT",
    pipeline: "sales",
    stageCode: "MG_NOCONQ",
    priority: "P1",
    profiles: fullOnly,
    kind: "plan_activity",
    name: "[MG] Ponów kontakt po kwalifikacji",
    execution: "parallel",
    timing: { mode: "after", value: 2, unit: "business_days", respectBusinessHours: true },
    settings: {
      activityType: "call",
      subject: "Ponów kontakt po kwalifikacji — {{Deal: Title}}",
      description: "Wróć do klienta i ustal pomiar albo przygotowanie oferty.",
      responsible: "Osoba odpowiedzialna za Deal",
      autoCompleteOnStageChange: true,
    },
    acceptance: ["Aktywność powstaje tylko dla Deali pozostających w tym etapie."],
  },
  {
    id: "S10_TASK_SCHEDULE_MEASUREMENT",
    pipeline: "sales",
    stageCode: "MG_MEASPLAN",
    priority: "P0",
    profiles: starterAndFull,
    kind: "create_task",
    name: "[MG] Ustal termin pomiaru",
    execution: "parallel",
    timing: { mode: "immediately", respectBusinessHours: true },
    settings: {
      title: "Ustal termin pomiaru — {{Deal: Title}}",
      description:
        "Skontaktuj się z klientem, ustal termin i uzupełnij pola Termin pomiaru oraz Osoba wykonująca pomiar.",
      deadline: "+1 dzień roboczy",
      assignee: "Osoba odpowiedzialna za Deal",
      linkToCrmItem: true,
    },
    acceptance: ["Po wejściu do etapu powstaje zadanie ustalenia pomiaru."],
  },
  {
    id: "S11_ACTIVITY_MEASUREMENT_REMINDER",
    pipeline: "sales",
    stageCode: "MG_MEASSET",
    priority: "P0",
    profiles: starterAndFull,
    kind: "plan_activity",
    name: "[MG] Przypomnienie o pomiarze",
    execution: "parallel",
    timing: { mode: "before_field", value: 1, unit: "days", fieldAlias: "MG_MEASUREMENT_AT", respectBusinessHours: true },
    conditions: [{ field: "MG_MEASUREMENT_AT", operator: "not_empty" }],
    settings: {
      activityType: "meeting",
      subject: "Pomiar u klienta — {{Deal: Title}}",
      description: "Potwierdź wizytę, przygotuj narzędzia i sprawdź adres montażu.",
      responsible: "Osoba odpowiedzialna za Deal lub osoba wykonująca pomiar",
      addToCalendar: true,
      autoCompleteOnStageChange: false,
    },
    acceptance: ["Reguła nie uruchamia się bez uzupełnionego pola Termin pomiaru."],
  },
  {
    id: "S12_TASK_PREPARE_OFFER_AFTER_MEASUREMENT",
    pipeline: "sales",
    stageCode: "MG_MEASDONE",
    priority: "P0",
    profiles: starterAndFull,
    kind: "create_task",
    name: "[MG] Przygotuj ofertę po pomiarze",
    execution: "parallel",
    timing: { mode: "immediately", respectBusinessHours: true },
    settings: {
      title: "Przygotuj ofertę po pomiarze — {{Deal: Title}}",
      description: "Uzupełnij notatki z pomiaru, sprawdź konfigurację i przygotuj ofertę dla klienta.",
      deadline: "+2 dni robocze",
      assignee: "Osoba odpowiedzialna za Deal",
      linkToCrmItem: true,
    },
    acceptance: ["Po zakończeniu pomiaru powstaje zadanie przygotowania oferty."],
  },
  {
    id: "S13_TASK_PREPARE_OFFER",
    pipeline: "sales",
    stageCode: "MG_OFFERPREP",
    priority: "P0",
    profiles: starterAndFull,
    kind: "create_task",
    name: "[MG] Przygotuj i zweryfikuj ofertę",
    execution: "parallel",
    timing: { mode: "immediately", respectBusinessHours: true },
    settings: {
      title: "Przygotuj i zweryfikuj ofertę — {{Deal: Title}}",
      description: "Sprawdź produkty, cenę, VAT, rabat, termin ważności i komplet danych klienta przed wysłaniem.",
      deadline: "+2 dni robocze",
      assignee: "Osoba odpowiedzialna za Deal",
      linkToCrmItem: true,
    },
    acceptance: ["Powstaje zadanie przygotowania oferty."],
  },
  {
    id: "S14_ACTIVITY_OFFER_FOLLOWUP",
    pipeline: "sales",
    stageCode: "MG_OFFERSENT",
    priority: "P0",
    profiles: starterAndFull,
    kind: "plan_activity",
    name: "[MG] Kontakt po wysłaniu oferty",
    execution: "parallel",
    timing: { mode: "after", value: 2, unit: "business_days", respectBusinessHours: true },
    settings: {
      activityType: "call",
      subject: "Kontakt po ofercie — {{Deal: Title}}",
      description: "Potwierdź odbiór oferty, zbierz uwagi i ustal dalszy krok.",
      responsible: "Osoba odpowiedzialna za Deal",
      autoCompleteOnStageChange: true,
    },
    acceptance: ["Po dwóch dniach roboczych pojawia się aktywność kontaktu, jeśli Deal nadal jest na etapie Oferta wysłana."],
  },
  {
    id: "S15_NOTIFY_OFFER_STALE",
    pipeline: "sales",
    stageCode: "MG_OFFERSENT",
    priority: "P1",
    profiles: fullOnly,
    kind: "notify_employee",
    name: "[MG] Oferta bez decyzji klienta",
    execution: "parallel",
    timing: { mode: "after", value: 7, unit: "business_days", respectBusinessHours: true },
    settings: {
      recipients: "Osoba odpowiedzialna za Deal",
      message: "Oferta dla {{Deal: Title}} nadal nie ma decyzji. Zaplanuj kontakt lub ustaw etap odroczenia/przegranej.",
    },
    acceptance: ["Powiadomienie nie uruchamia się po opuszczeniu etapu Oferta wysłana."],
  },
  {
    id: "S16_ACTIVITY_CONTRACT_FOLLOWUP",
    pipeline: "sales",
    stageCode: "MG_CONTRACT",
    priority: "P0",
    profiles: starterAndFull,
    kind: "plan_activity",
    name: "[MG] Potwierdź umowę lub zaliczkę",
    execution: "parallel",
    timing: { mode: "after", value: 2, unit: "business_days", respectBusinessHours: true },
    settings: {
      activityType: "call",
      subject: "Potwierdź umowę / zaliczkę — {{Deal: Title}}",
      description: "Potwierdź podpisanie dokumentów, proformę i termin wpłaty zaliczki.",
      responsible: "Osoba odpowiedzialna za Deal",
      autoCompleteOnStageChange: true,
    },
    acceptance: ["Po dwóch dniach roboczych pojawia się aktywność kontrolna."],
  },
  {
    id: "S17_ACTIVITY_DEFERRED_TIME",
    pipeline: "sales",
    stageCode: "MG_DELAYTIME",
    priority: "P0",
    profiles: starterAndFull,
    kind: "plan_activity",
    name: "[MG] Powrót do klienta — termin",
    execution: "parallel",
    timing: { mode: "at_field", fieldAlias: "MG_DEFERRED_UNTIL", respectBusinessHours: true },
    conditions: [{ field: "MG_DEFERRED_UNTIL", operator: "not_empty" }],
    settings: {
      activityType: "call",
      subject: "Powrót do klienta — {{Deal: Title}}",
      description: "Skontaktuj się zgodnie z ustalonym terminem odroczenia.",
      responsible: "Osoba odpowiedzialna za Deal",
      autoCompleteOnStageChange: true,
    },
    acceptance: ["Reguła korzysta z pola Powrót do klienta i nie uruchamia się przy pustym polu."],
  },
  {
    id: "S18_ACTIVITY_DEFERRED_BUDGET",
    pipeline: "sales",
    stageCode: "MG_DELAYCASH",
    priority: "P0",
    profiles: starterAndFull,
    kind: "plan_activity",
    name: "[MG] Powrót do klienta — budżet",
    execution: "parallel",
    timing: { mode: "at_field", fieldAlias: "MG_DEFERRED_UNTIL", respectBusinessHours: true },
    conditions: [{ field: "MG_DEFERRED_UNTIL", operator: "not_empty" }],
    settings: {
      activityType: "call",
      subject: "Powrót do klienta w sprawie budżetu — {{Deal: Title}}",
      description: "Wróć do klienta w uzgodnionym terminie i sprawdź aktualną możliwość realizacji.",
      responsible: "Osoba odpowiedzialna za Deal",
      autoCompleteOnStageChange: true,
    },
    acceptance: ["Reguła korzysta z pola Powrót do klienta."],
  },
  {
    id: "S19_END_SALES_TASKS_WON",
    pipeline: "sales",
    stageCode: "MG_WON",
    priority: "P0",
    profiles: starterAndFull,
    kind: "end_tasks",
    name: "[MG] Zakończ zadania sprzedażowe",
    execution: "sequential",
    timing: { mode: "immediately" },
    settings: {
      pipeline: "01 Sprzedaż z pomiarem",
      stages: "Wszystkie wcześniejsze etapy sprzedażowe",
    },
    acceptance: ["Otwarte zadania utworzone przez roboty sprzedażowe są zamykane."],
  },
  {
    id: "S20_TUNNEL_TO_REALIZATION",
    pipeline: "sales",
    stageCode: "MG_WON",
    priority: "P0",
    profiles: starterAndFull,
    kind: "sales_tunnel_move",
    name: "[MG] Przenieś wygrany Deal do realizacji",
    execution: "sequential",
    timing: { mode: "immediately" },
    settings: {
      operation: "MOVE",
      targetPipeline: "02 Realizacja",
      targetStage: "W realizacji",
      responsible: "Pozostaw bieżącą osobę odpowiedzialną",
      warning:
        "Użyj Przenieś, nie Kopiuj. Kopia zachowałaby to samo ID zapytania MoonGlass w dwóch Dealach i mogłaby powodować konflikt synchronizacji.",
    },
    acceptance: [
      "Po oznaczeniu sprzedaży jako wygranej ten sam Deal trafia do lejka 02 Realizacja.",
      "Nie powstaje drugi Deal z tym samym ID zapytania ze strony.",
    ],
  },
  {
    id: "S21_END_TASKS_LOST",
    pipeline: "sales",
    stageCode: "MG_BADFIT",
    priority: "P1",
    profiles: fullOnly,
    kind: "end_tasks",
    name: "[MG] Zakończ zadania po przegranej",
    execution: "parallel",
    timing: { mode: "immediately" },
    settings: { pipeline: "01 Sprzedaż z pomiarem", stages: "Wszystkie etapy sprzedażowe" },
    acceptance: ["Otwarte zadania automatyzacji sprzedaży są zamykane."],
    notes: ["Skopiuj tę regułę również do pozostałych etapów przegranych."],
  },

  {
    id: "R01_TASK_REALIZATION_START",
    pipeline: "realization",
    stageCode: "MG_REAL",
    priority: "P0",
    profiles: starterAndFull,
    kind: "create_task",
    name: "[MG] Sprawdź komplet realizacji",
    execution: "parallel",
    timing: { mode: "immediately", respectBusinessHours: true },
    settings: {
      title: "Sprawdź komplet realizacji — {{Deal: Title}}",
      description: "Zweryfikuj ofertę, wpłatę, pomiar, dokumenty, adres i zakres zamówienia przed zamówieniem materiału.",
      deadline: "+1 dzień roboczy",
      assignee: "Osoba odpowiedzialna za Deal",
      linkToCrmItem: true,
    },
    acceptance: ["Po wejściu do realizacji powstaje zadanie kontroli kompletności."],
  },
  {
    id: "R02_TASK_GLASS_DIMENSIONS",
    pipeline: "realization",
    stageCode: "MG_GLASS",
    priority: "P1",
    profiles: fullOnly,
    kind: "create_task",
    name: "[MG] Przygotuj wymiary szkła",
    execution: "parallel",
    timing: { mode: "immediately", respectBusinessHours: true },
    settings: {
      title: "Przygotuj wymiary szkła — {{Deal: Title}}",
      description: "Zweryfikuj notatki z pomiaru i przygotuj komplet wymiarów do zamówienia.",
      deadline: "+1 dzień roboczy",
      assignee: "Osoba odpowiedzialna za Deal",
      linkToCrmItem: true,
    },
    acceptance: ["Powstaje zadanie przygotowania wymiarów."],
  },
  {
    id: "R03_TASK_SEND_MATERIAL_QUOTE",
    pipeline: "realization",
    stageCode: "MG_SENDMAT",
    priority: "P0",
    profiles: starterAndFull,
    kind: "create_task",
    name: "[MG] Wyślij materiał do wyceny",
    execution: "parallel",
    timing: { mode: "immediately", respectBusinessHours: true },
    settings: {
      title: "Wyślij materiał do wyceny — {{Deal: Title}}",
      description: "Przygotuj komplet danych i wyślij zapytanie do dostawcy.",
      deadline: "+1 dzień roboczy",
      assignee: "Osoba odpowiedzialna za Deal",
      linkToCrmItem: true,
    },
    acceptance: ["Powstaje zadanie wysłania wyceny materiału."],
  },
  {
    id: "R04_ACTIVITY_MATERIAL_QUOTE_FOLLOWUP",
    pipeline: "realization",
    stageCode: "MG_MATQUOTE",
    priority: "P0",
    profiles: starterAndFull,
    kind: "plan_activity",
    name: "[MG] Sprawdź status wyceny materiału",
    execution: "parallel",
    timing: { mode: "after", value: 2, unit: "business_days", respectBusinessHours: true },
    settings: {
      activityType: "call",
      subject: "Sprawdź wycenę materiału — {{Deal: Title}}",
      description: "Skontaktuj się z dostawcą i zaktualizuj status materiału.",
      responsible: "Osoba odpowiedzialna za Deal",
      autoCompleteOnStageChange: true,
    },
    acceptance: ["Po dwóch dniach pojawia się przypomnienie o wycenie materiału."],
  },
  {
    id: "R05_TASK_ORDER_MATERIAL",
    pipeline: "realization",
    stageCode: "MG_MATOK",
    priority: "P0",
    profiles: starterAndFull,
    kind: "create_task",
    name: "[MG] Zamów zaakceptowany materiał",
    execution: "parallel",
    timing: { mode: "immediately", respectBusinessHours: true },
    settings: {
      title: "Zamów zaakceptowany materiał — {{Deal: Title}}",
      description: "Sprawdź akceptację kosztu i przygotuj zamówienie u dostawcy.",
      deadline: "+1 dzień roboczy",
      assignee: "Osoba odpowiedzialna za Deal",
      linkToCrmItem: true,
    },
    acceptance: ["Powstaje zadanie zamówienia materiału."],
  },
  {
    id: "R06_TASK_PLACE_ORDER",
    pipeline: "realization",
    stageCode: "MG_ORDERMAT",
    priority: "P1",
    profiles: fullOnly,
    kind: "create_task",
    name: "[MG] Złóż zamówienie u dostawcy",
    execution: "parallel",
    timing: { mode: "immediately", respectBusinessHours: true },
    settings: {
      title: "Złóż zamówienie u dostawcy — {{Deal: Title}}",
      description: "Złóż zamówienie i zapisz potwierdzenie oraz przewidywany termin dostawy.",
      deadline: "+1 dzień roboczy",
      assignee: "Osoba odpowiedzialna za Deal",
      linkToCrmItem: true,
    },
    acceptance: ["Powstaje zadanie złożenia zamówienia."],
  },
  {
    id: "R07_ACTIVITY_CHECK_DELIVERY",
    pipeline: "realization",
    stageCode: "MG_MATORDER",
    priority: "P1",
    profiles: fullOnly,
    kind: "plan_activity",
    name: "[MG] Sprawdź termin dostawy materiału",
    execution: "parallel",
    timing: { mode: "after", value: 5, unit: "business_days", respectBusinessHours: true },
    settings: {
      activityType: "call",
      subject: "Sprawdź dostawę materiału — {{Deal: Title}}",
      description: "Zweryfikuj status zamówienia u dostawcy i zaktualizuj termin realizacji.",
      responsible: "Osoba odpowiedzialna za Deal",
      autoCompleteOnStageChange: true,
    },
    acceptance: ["Przypomnienie nie uruchamia się po opuszczeniu etapu."],
  },
  {
    id: "R08_ACTIVITY_INSTALLATION_REMINDER",
    pipeline: "realization",
    stageCode: "MG_TEAMDATE",
    priority: "P0",
    profiles: starterAndFull,
    kind: "plan_activity",
    name: "[MG] Potwierdź ekipę i termin montażu",
    execution: "parallel",
    timing: { mode: "before_field", value: 1, unit: "days", fieldAlias: "MG_INSTALLATION_FROM", respectBusinessHours: true },
    conditions: [{ field: "MG_INSTALLATION_FROM", operator: "not_empty" }],
    settings: {
      activityType: "meeting",
      subject: "Montaż — {{Deal: Title}}",
      description: "Potwierdź termin z klientem i ekipą, materiał oraz dojazd.",
      responsible: "Osoba odpowiedzialna za Deal",
      addToCalendar: true,
      autoCompleteOnStageChange: false,
    },
    acceptance: ["Reguła uruchamia się wyłącznie z uzupełnionym polem Montaż od."],
  },
  {
    id: "R09_ACTIVITY_PAUSED_RETURN",
    pipeline: "realization",
    stageCode: "MG_PAUSED",
    priority: "P1",
    profiles: fullOnly,
    kind: "plan_activity",
    name: "[MG] Powrót do zawieszonej realizacji",
    execution: "parallel",
    timing: { mode: "at_field", fieldAlias: "MG_DEFERRED_UNTIL", respectBusinessHours: true },
    conditions: [{ field: "MG_DEFERRED_UNTIL", operator: "not_empty" }],
    settings: {
      activityType: "call",
      subject: "Wróć do zawieszonej realizacji — {{Deal: Title}}",
      description: "Sprawdź, czy można wznowić realizację i zaktualizuj etap.",
      responsible: "Osoba odpowiedzialna za Deal",
      autoCompleteOnStageChange: true,
    },
    acceptance: ["Reguła korzysta z pola Powrót do klienta."],
  },
  {
    id: "R10_TASK_INSTALLATION_DOCUMENTATION",
    pipeline: "realization",
    stageCode: "MG_INSTALL",
    priority: "P0",
    profiles: starterAndFull,
    kind: "create_task",
    name: "[MG] Dokumentacja montażu",
    execution: "parallel",
    timing: { mode: "immediately", respectBusinessHours: true },
    settings: {
      title: "Dokumentacja montażu — {{Deal: Title}}",
      description: "Wykonaj zdjęcia, zbierz protokół, wpisz usterki i potwierdź zakończenie prac.",
      deadline: "Data z pola Montaż do; jeśli pusta: +2 dni robocze",
      assignee: "Osoba odpowiedzialna za Deal",
      linkToCrmItem: true,
    },
    acceptance: ["Po rozpoczęciu montażu powstaje zadanie dokumentacji."],
  },
  {
    id: "R11_ACTIVITY_PAYMENT_FOLLOWUP",
    pipeline: "realization",
    stageCode: "MG_DONEUNP",
    priority: "P0",
    profiles: starterAndFull,
    kind: "plan_activity",
    name: "[MG] Rozlicz pozostałą płatność",
    execution: "parallel",
    timing: { mode: "immediately", respectBusinessHours: true },
    settings: {
      activityType: "call",
      subject: "Rozliczenie po montażu — {{Deal: Title}}",
      description: "Skontaktuj się w sprawie pozostałej płatności i uzupełnij kwotę wpłaconą.",
      responsible: "Osoba odpowiedzialna za Deal",
      autoCompleteOnStageChange: true,
    },
    acceptance: ["Po wejściu do etapu pojawia się aktywność rozliczeniowa."],
  },
  {
    id: "R12_TASK_CONFIRM_CASH",
    pipeline: "realization",
    stageCode: "MG_DONECASH",
    priority: "P1",
    profiles: fullOnly,
    kind: "create_task",
    name: "[MG] Potwierdź odbiór gotówki",
    execution: "parallel",
    timing: { mode: "immediately", respectBusinessHours: true },
    settings: {
      title: "Potwierdź odbiór gotówki — {{Deal: Title}}",
      description: "Zapisz kwotę, osobę odbierającą i potwierdzenie rozliczenia.",
      deadline: "Koniec bieżącego dnia roboczego",
      assignee: "Osoba odpowiedzialna za Deal",
      linkToCrmItem: true,
    },
    acceptance: ["Powstaje zadanie potwierdzenia gotówki."],
  },
  {
    id: "R13_TASK_CLOSE_DOCUMENTATION",
    pipeline: "realization",
    stageCode: "MG_PROJECTOK",
    priority: "P0",
    profiles: starterAndFull,
    kind: "create_task",
    name: "[MG] Zamknij dokumentację projektu",
    execution: "parallel",
    timing: { mode: "immediately", respectBusinessHours: true },
    settings: {
      title: "Zamknij dokumentację projektu — {{Deal: Title}}",
      description: "Sprawdź płatności, zdjęcia, protokół, dokumenty i ewentualne usterki przed zamknięciem projektu.",
      deadline: "+1 dzień roboczy",
      assignee: "Osoba odpowiedzialna za Deal",
      linkToCrmItem: true,
    },
    acceptance: ["Powstaje zadanie kontroli przed zamknięciem."],
  },
  {
    id: "R14_END_TASKS_CLOSED",
    pipeline: "realization",
    stageCode: "MG_CLOSED",
    priority: "P0",
    profiles: starterAndFull,
    kind: "end_tasks",
    name: "[MG] Zakończ zadania realizacji",
    execution: "parallel",
    timing: { mode: "immediately" },
    settings: { pipeline: "02 Realizacja", stages: "Wszystkie wcześniejsze etapy realizacji" },
    acceptance: ["Po zamknięciu projektu nie pozostają otwarte zadania robotów realizacyjnych."],
  },
  {
    id: "R15_HISTORY_CLOSED",
    pipeline: "realization",
    stageCode: "MG_CLOSED",
    priority: "P1",
    profiles: fullOnly,
    kind: "add_history_entry",
    name: "[MG] Wpis o zamknięciu projektu",
    execution: "parallel",
    timing: { mode: "immediately" },
    settings: {
      text: "Projekt został zamknięty automatyzacją MoonGlass. Sprawdź komplet dokumentów i płatności w karcie Deala.",
      createdBy: "Osoba odpowiedzialna za Deal",
    },
    acceptance: ["W historii Deala pojawia się wpis o zamknięciu."],
  },

  {
    id: "C01_TASK_VERIFY_COMPLAINT",
    pipeline: "complaints",
    stageCode: "MG_CLAIM",
    priority: "P0",
    profiles: starterAndFull,
    kind: "create_task",
    name: "[MG] Zweryfikuj reklamację",
    execution: "parallel",
    timing: { mode: "immediately", respectBusinessHours: true },
    settings: {
      title: "Zweryfikuj reklamację — {{Deal: Title}}",
      description: "Skontaktuj się z klientem, zbierz zdjęcia, opis, datę zdarzenia i dokumenty realizacji.",
      deadline: "+1 dzień roboczy",
      assignee: "Osoba odpowiedzialna za Deal",
      linkToCrmItem: true,
    },
    acceptance: ["Nowa reklamacja otrzymuje zadanie weryfikacji."],
  },
  {
    id: "C02_TASK_ANALYZE_COMPLAINT",
    pipeline: "complaints",
    stageCode: "MG_ANALYZE",
    priority: "P0",
    profiles: starterAndFull,
    kind: "create_task",
    name: "[MG] Analiza reklamacji",
    execution: "parallel",
    timing: { mode: "immediately", respectBusinessHours: true },
    settings: {
      title: "Analiza reklamacji — {{Deal: Title}}",
      description: "Ustal przyczynę, odpowiedzialność, wymagane materiały i rekomendowaną decyzję.",
      deadline: "+2 dni robocze",
      assignee: "Osoba odpowiedzialna za Deal",
      linkToCrmItem: true,
    },
    acceptance: ["Powstaje zadanie analizy zgłoszenia."],
  },
  {
    id: "C03_TASK_PLAN_REPAIR",
    pipeline: "complaints",
    stageCode: "MG_ACCEPT",
    priority: "P0",
    profiles: starterAndFull,
    kind: "create_task",
    name: "[MG] Zaplanuj sposób naprawy",
    execution: "parallel",
    timing: { mode: "immediately", respectBusinessHours: true },
    settings: {
      title: "Zaplanuj naprawę reklamacyjną — {{Deal: Title}}",
      description: "Ustal zakres, materiały, ekipę i przewidywany termin naprawy.",
      deadline: "+1 dzień roboczy",
      assignee: "Osoba odpowiedzialna za Deal",
      linkToCrmItem: true,
    },
    acceptance: ["Uznana reklamacja otrzymuje zadanie planowania naprawy."],
  },
  {
    id: "C04_TASK_ORDER_CLAIM_MATERIAL",
    pipeline: "complaints",
    stageCode: "MG_NEEDMAT",
    priority: "P0",
    profiles: starterAndFull,
    kind: "create_task",
    name: "[MG] Zamów towar reklamacyjny",
    execution: "parallel",
    timing: { mode: "immediately", respectBusinessHours: true },
    settings: {
      title: "Zamów towar reklamacyjny — {{Deal: Title}}",
      description: "Zamów wymagane elementy i zapisz potwierdzenie oraz przewidywany termin dostawy.",
      deadline: "+1 dzień roboczy",
      assignee: "Osoba odpowiedzialna za Deal",
      linkToCrmItem: true,
    },
    acceptance: ["Powstaje zadanie zamówienia towaru."],
  },
  {
    id: "C05_ACTIVITY_CLAIM_DELIVERY",
    pipeline: "complaints",
    stageCode: "MG_CMATORD",
    priority: "P1",
    profiles: fullOnly,
    kind: "plan_activity",
    name: "[MG] Sprawdź dostawę towaru reklamacyjnego",
    execution: "parallel",
    timing: { mode: "after", value: 5, unit: "business_days", respectBusinessHours: true },
    settings: {
      activityType: "call",
      subject: "Sprawdź towar reklamacyjny — {{Deal: Title}}",
      description: "Zweryfikuj status dostawy i ustal termin naprawy.",
      responsible: "Osoba odpowiedzialna za Deal",
      autoCompleteOnStageChange: true,
    },
    acceptance: ["Po pięciu dniach powstaje przypomnienie, jeśli towar nadal jest zamówiony."],
  },
  {
    id: "C06_ACTIVITY_REPAIR_REMINDER",
    pipeline: "complaints",
    stageCode: "MG_FIXDATE",
    priority: "P0",
    profiles: starterAndFull,
    kind: "plan_activity",
    name: "[MG] Przypomnienie o naprawie",
    execution: "parallel",
    timing: { mode: "before_field", value: 1, unit: "days", fieldAlias: "MG_NEXT_VISIT_AT", respectBusinessHours: true },
    conditions: [{ field: "MG_NEXT_VISIT_AT", operator: "not_empty" }],
    settings: {
      activityType: "meeting",
      subject: "Naprawa reklamacyjna — {{Deal: Title}}",
      description: "Potwierdź termin z klientem i ekipą oraz komplet materiałów.",
      responsible: "Osoba odpowiedzialna za Deal",
      addToCalendar: true,
      autoCompleteOnStageChange: false,
    },
    acceptance: ["Reguła uruchamia się tylko przy uzupełnionej dacie Najbliższa wizyta."],
  },
  {
    id: "C07_TASK_REPAIR_PROTOCOL",
    pipeline: "complaints",
    stageCode: "MG_FIXING",
    priority: "P0",
    profiles: starterAndFull,
    kind: "create_task",
    name: "[MG] Protokół naprawy reklamacyjnej",
    execution: "parallel",
    timing: { mode: "immediately", respectBusinessHours: true },
    settings: {
      title: "Protokół naprawy reklamacyjnej — {{Deal: Title}}",
      description: "Wykonaj zdjęcia przed/po, opisz wykonane prace i zbierz potwierdzenie klienta.",
      deadline: "+1 dzień roboczy",
      assignee: "Osoba odpowiedzialna za Deal",
      linkToCrmItem: true,
    },
    acceptance: ["Po rozpoczęciu naprawy powstaje zadanie dokumentacji."],
  },
  {
    id: "C08_TASK_REJECTION_REASON",
    pipeline: "complaints",
    stageCode: "MG_REJECT",
    priority: "P1",
    profiles: fullOnly,
    kind: "create_task",
    name: "[MG] Przygotuj uzasadnienie odrzucenia",
    execution: "parallel",
    timing: { mode: "immediately", respectBusinessHours: true },
    settings: {
      title: "Uzasadnienie odrzucenia reklamacji — {{Deal: Title}}",
      description: "Przygotuj czytelne uzasadnienie, podstawę decyzji i komunikację do klienta.",
      deadline: "+1 dzień roboczy",
      assignee: "Osoba odpowiedzialna za Deal",
      linkToCrmItem: true,
    },
    acceptance: ["Powstaje zadanie przygotowania uzasadnienia."],
  },
  {
    id: "C09_TASK_INTERNAL_ANALYSIS",
    pipeline: "complaints",
    stageCode: "MG_FAILAN",
    priority: "P1",
    profiles: fullOnly,
    kind: "create_task",
    name: "[MG] Analiza wewnętrzna przyczyny",
    execution: "parallel",
    timing: { mode: "immediately", respectBusinessHours: true },
    settings: {
      title: "Analiza przyczyny reklamacji — {{Deal: Title}}",
      description: "Zapisz przyczynę, koszt, odpowiedzialność i działanie zapobiegawcze dla przyszłych realizacji.",
      deadline: "+3 dni robocze",
      assignee: "Osoba odpowiedzialna za Deal",
      linkToCrmItem: true,
    },
    acceptance: ["Powstaje zadanie analizy wewnętrznej."],
  },
  {
    id: "C10_END_TASKS_CLOSED",
    pipeline: "complaints",
    stageCode: "MG_CLAIMOK",
    priority: "P0",
    profiles: starterAndFull,
    kind: "end_tasks",
    name: "[MG] Zakończ zadania reklamacji",
    execution: "parallel",
    timing: { mode: "immediately" },
    settings: { pipeline: "03 Reklamacje", stages: "Wszystkie wcześniejsze etapy reklamacji" },
    acceptance: ["Po zamknięciu reklamacji nie pozostają otwarte zadania utworzone przez roboty."],
  },
];

export function getAutomationRules(profile: AutomationProfile): AutomationRuleBlueprint[] {
  return MOONGLASS_AUTOMATION_RULES.filter((rule) => rule.profiles.includes(profile));
}
